# Server properties
server:
  servlet:
    context-path: /
  port: 8080

# Spring properties
spring:
  # h2 is active by default. This value can be overwritten by java arg param
  profiles:
    active: heroku
  application:
    name: gestion-proyectos-investigacion-back
  messages:
    basename: bundles/apiLanguageBundle